name: test

on: push
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: ğŸ‘¾ Clone repo to runner
      uses: actions/checkout@v4

    - name: ğŸ Install python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: ğŸ‘€ Check python version
      run: python --version
    
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: ğŸ‘€ Check that poetry is installed
      run: poetry --help

    - name: ğŸ—ï¸ Install dependencies using Poetry
      run: poetry install --with dev,docs
    
    - name: ğŸ¤– Run tests
      run: |
        source .venv/bin/activate
        pytest --help
        # pytest tests/
        # coverage report
